# Generated by Django 4.1.4 on 2023-01-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu_intro", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mytext",
            name="head_image",
            field=models.ImageField(blank=True, upload_to="edu_intro/images/%Y/%m/%d/"),
        ),
    ]
